# =============================================================================
#  SwishAI — Extended app.py
#  Original project by sPappalard (https://github.com/sPappalard/SwishAI)
#  Extended with: ByteTrack player IDs, shot attribution per player,
#                 2D court minimap, and per-player stats panel overlay.
#
#  DROP-IN REPLACEMENT for BE/app.py
#  All original endpoints, processing modes, and confidence configs preserved.
#
#  NEW dependencies (add to requirements.txt):
#      lapx>=0.5.5          <- ByteTrack dependency for Ultralytics
#
#  NEW files expected in BE/:
#      homography.npy       <- generated by calibrate.py (run ONCE first)
#
#  USAGE:
#      1. Run calibrate.py on a sample frame to generate homography.npy
#      2. Activate your venv, then: python app.py
# =============================================================================

import os
import time
import uuid
import threading
import traceback
from pathlib import Path
from collections import defaultdict

import cv2
import numpy as np
import uvicorn
from fastapi import FastAPI, File, UploadFile, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse, JSONResponse
from pydantic import BaseModel
from ultralytics import YOLO

# ---------------------------------------------------------------------------
# App & CORS (identical to original)
# ---------------------------------------------------------------------------
app = FastAPI(title="SwishAI Extended")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
BASE_DIR        = Path(__file__).parent
UPLOAD_DIR      = BASE_DIR / "uploads"
PROCESSED_DIR   = BASE_DIR / "processed"
WEIGHTS_PATH    = BASE_DIR / "basketball_training" / "weights" / "best.pt"
HOMOGRAPHY_PATH = BASE_DIR / "homography.npy"

UPLOAD_DIR.mkdir(exist_ok=True)
PROCESSED_DIR.mkdir(exist_ok=True)

# ---------------------------------------------------------------------------
# Model (loaded once at startup)
# ---------------------------------------------------------------------------
print("[SwishAI] Loading YOLO model...")
model = YOLO(str(WEIGHTS_PATH))
print("[SwishAI] Model loaded.")

# ---------------------------------------------------------------------------
# Detection class IDs (matching SwishAI training dataset)
# ---------------------------------------------------------------------------
CLASS_BALL           = 0
CLASS_BALL_IN_BASKET = 1
CLASS_PLAYER         = 2
CLASS_BASKET         = 3
CLASS_PLAYER_SHOOT   = 4

# ---------------------------------------------------------------------------
# Default confidence thresholds (original SwishAI values)
# ---------------------------------------------------------------------------
DEFAULT_CONF = {
    CLASS_BALL:           0.60,
    CLASS_BALL_IN_BASKET: 0.25,
    CLASS_PLAYER:         0.70,
    CLASS_BASKET:         0.70,
    CLASS_PLAYER_SHOOT:   0.77,
}

# ---------------------------------------------------------------------------
# Global processing state (identical structure to original)
# ---------------------------------------------------------------------------
processing_state = {
    "status":        "idle",       # idle | processing | completed | error
    "progress":      0,
    "output_file":   None,
    "error":         None,
    # Per-player stats (NEW)
    "player_stats":  {},
    # Global totals (kept for API back-compat)
    "total_shots":   0,
    "total_scores":  0,
    "fg_percentage": 0.0,
}
state_lock = threading.Lock()


# ---------------------------------------------------------------------------
# Pydantic request schemas
# ---------------------------------------------------------------------------
class ProcessRequest(BaseModel):
    filename:        str
    mode:            str   = "full"      # full | stats_effects | stats_only
    test_mode:       bool  = False
    conf_ball:       float = DEFAULT_CONF[CLASS_BALL]
    conf_in_basket:  float = DEFAULT_CONF[CLASS_BALL_IN_BASKET]
    conf_player:     float = DEFAULT_CONF[CLASS_PLAYER]
    conf_basket:     float = DEFAULT_CONF[CLASS_BASKET]
    conf_shoot:      float = DEFAULT_CONF[CLASS_PLAYER_SHOOT]


# ===========================================================================
#  COURT MINIMAP RENDERER
# ===========================================================================

# Half-court real-world dimensions in cm (NBA standard, used for homography)
# You can change these to match your actual court if it's non-standard.
COURT_W_CM = 1500   # 15 m wide (full court width)
COURT_H_CM = 1400   # 14 m deep (half-court length)

# Minimap canvas size in pixels
MAP_W = 300
MAP_H = 280

# Scale factors: real-world cm → minimap pixels
SCALE_X = MAP_W / COURT_W_CM
SCALE_Y = MAP_H / COURT_H_CM

# Player dot colors (BGR) — cycles for up to 10 players
PLAYER_COLORS = [
    (0,   200, 255),   # yellow-ish
    (255, 100,   0),   # blue
    (0,   255, 100),   # green
    (0,    80, 255),   # red
    (255,   0, 200),   # magenta
    (0,   200,   0),   # dark green
    (200,   0, 255),   # purple
    (0,   150, 255),   # orange
    (255, 255,   0),   # cyan
    (100, 100, 255),   # salmon
]


def get_player_color(player_id: int):
    return PLAYER_COLORS[int(player_id) % len(PLAYER_COLORS)]


def draw_court_base() -> np.ndarray:
    """
    Draw a top-down half-court diagram on a dark canvas.
    All measurements scaled from real-world cm to MAP_W x MAP_H pixels.
    Returns a BGR image.
    """
    court = np.zeros((MAP_H, MAP_W, 3), dtype=np.uint8)
    court[:] = (30, 30, 30)   # dark background

    def cx(cm): return int(cm * SCALE_X)
    def cy(cm): return int(cm * SCALE_Y)

    LINE = (180, 180, 180)
    PAINT = (50, 50, 80)

    # Court boundary
    cv2.rectangle(court, (0, 0), (MAP_W - 1, MAP_H - 1), LINE, 1)

    # Paint / key (roughly 490 cm wide, 575 cm deep — NBA proportions scaled)
    paint_x1 = cx(505)
    paint_x2 = cx(995)
    cv2.rectangle(court, (paint_x1, 0), (paint_x2, cy(575)), PAINT, -1)
    cv2.rectangle(court, (paint_x1, 0), (paint_x2, cy(575)), LINE, 1)

    # Free-throw circle (radius ~180 cm)
    ft_center = (cx(750), cy(575))
    cv2.circle(court, ft_center, cx(180), LINE, 1)

    # Basket (small filled circle near top edge, centered)
    basket_pt = (cx(750), cy(157))
    cv2.circle(court, basket_pt, 8, (0, 120, 255), -1)
    cv2.circle(court, basket_pt, 8, LINE, 1)

    # Backboard line
    cv2.line(court,
             (cx(660), cy(90)), (cx(840), cy(90)),
             (200, 200, 200), 2)

    # Three-point arc — approximated as an arc + two straight side lines
    # NBA: 3pt line is 723 cm from basket center, cut-off at sidelines ~90 cm from baseline
    arc_center = basket_pt
    arc_radius = cx(723)
    cv2.ellipse(court, arc_center, (arc_radius, arc_radius),
                0, 0, 180, LINE, 1)

    # Label
    cv2.putText(court, "COURT MAP", (5, MAP_H - 6),
                cv2.FONT_HERSHEY_SIMPLEX, 0.35, (140, 140, 140), 1)

    return court


def project_to_minimap(foot_px: tuple, H: np.ndarray) -> tuple | None:
    """
    Transform a pixel point (foot of player bbox) to minimap coordinates
    using the homography matrix H.
    Returns (map_x, map_y) or None if transform fails.
    """
    try:
        pt = np.array([[[float(foot_px[0]), float(foot_px[1])]]], dtype=np.float32)
        dst = cv2.perspectiveTransform(pt, H)
        real_x, real_y = dst[0][0]   # coordinates in cm on court
        map_x = int(real_x * SCALE_X)
        map_y = int(real_y * SCALE_Y)
        if 0 <= map_x < MAP_W and 0 <= map_y < MAP_H:
            return (map_x, map_y)
        return None
    except Exception:
        return None


# ===========================================================================
#  STATS PANEL RENDERER
# ===========================================================================

PANEL_W = 300
PANEL_BG = (20, 20, 20)


def draw_stats_panel(player_stats: dict, total_shots: int,
                     total_scores: int, fg_pct: float,
                     panel_h: int) -> np.ndarray:
    """
    Render a dark stats panel showing:
      - Global totals row
      - Per-player table: ID | Shots | Scores | FG%
    Returns a BGR image of size (panel_h, PANEL_W).
    """
    panel = np.zeros((panel_h, PANEL_W, 3), dtype=np.uint8)
    panel[:] = PANEL_BG

    # ---- Header ----
    cv2.rectangle(panel, (0, 0), (PANEL_W, 36), (40, 40, 40), -1)
    cv2.putText(panel, "SwishAI  |  Player Stats",
                (8, 24), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255, 180, 0), 1)

    # ---- Global totals ----
    y = 55
    cv2.putText(panel, f"Total Shots : {total_shots}",
                (10, y), cv2.FONT_HERSHEY_SIMPLEX, 0.45, (200, 200, 200), 1)
    y += 20
    cv2.putText(panel, f"Total Scores: {total_scores}",
                (10, y), cv2.FONT_HERSHEY_SIMPLEX, 0.45, (200, 200, 200), 1)
    y += 20
    cv2.putText(panel, f"Overall FG% : {fg_pct:.1f}%",
                (10, y), cv2.FONT_HERSHEY_SIMPLEX, 0.45, (255, 180, 0), 1)

    # ---- Divider ----
    y += 14
    cv2.line(panel, (10, y), (PANEL_W - 10, y), (80, 80, 80), 1)
    y += 14

    # ---- Per-player table header ----
    cv2.putText(panel, "ID   Shots  Made   FG%",
                (10, y), cv2.FONT_HERSHEY_SIMPLEX, 0.4, (160, 160, 160), 1)
    y += 4
    cv2.line(panel, (10, y), (PANEL_W - 10, y), (60, 60, 60), 1)
    y += 12

    # ---- Per-player rows ----
    sorted_players = sorted(player_stats.items(), key=lambda x: -x[1]["shots"])
    for pid, stats in sorted_players:
        if y + 18 > panel_h - 10:
            break
        shots  = stats["shots"]
        scores = stats["scores"]
        pct    = (scores / shots * 100) if shots > 0 else 0.0
        color  = get_player_color(pid)
        row_txt = f"P{pid:<3}  {shots:<6} {scores:<6} {pct:.1f}%"
        cv2.putText(panel, row_txt,
                    (10, y), cv2.FONT_HERSHEY_SIMPLEX, 0.42, color, 1)
        y += 18

    return panel


# ===========================================================================
#  PULSE / SCORE ANIMATION  (preserved from original SwishAI)
# ===========================================================================

class PulseEffect:
    """Draws an expanding ring at the basket when a score is registered."""
    def __init__(self, center: tuple, max_radius: int = 80, duration: int = 20):
        self.center     = center
        self.max_radius = max_radius
        self.duration   = duration
        self.frame      = 0

    @property
    def active(self):
        return self.frame < self.duration

    def draw(self, img: np.ndarray):
        if not self.active:
            return
        t      = self.frame / self.duration
        radius = int(t * self.max_radius)
        alpha  = int(255 * (1 - t))
        overlay = img.copy()
        cv2.circle(overlay, self.center, radius, (0, 200, 255), 3)
        cv2.addWeighted(overlay, alpha / 255, img, 1 - alpha / 255, 0, img)
        self.frame += 1


# ===========================================================================
#  CORE VIDEO PROCESSING
# ===========================================================================

def _get_foot_point(box) -> tuple:
    """Return the bottom-center pixel of a bounding box (player's foot)."""
    x1, y1, x2, y2 = box
    return (int((x1 + x2) / 2), int(y2))


def process_video(input_path: str, output_path: str, mode: str,
                  test_mode: bool, conf_map: dict):
    """
    Main processing loop.
    Replaces the original SwishAI predict loop with model.track() so every
    detected player gets a stable ByteTrack ID across frames.
    """
    global processing_state

    # ---- Load homography (optional — minimap disabled if missing) ----
    H = None
    if HOMOGRAPHY_PATH.exists():
        H = np.load(str(HOMOGRAPHY_PATH))
        print(f"[SwishAI] Homography loaded from {HOMOGRAPHY_PATH}")
    else:
        print("[SwishAI] WARNING: homography.npy not found. "
              "Run calibrate.py first. Minimap will be disabled.")

    cap = cv2.VideoCapture(input_path)
    if not cap.isOpened():
        raise RuntimeError(f"Cannot open video: {input_path}")

    fps        = cap.get(cv2.CAP_PROP_FPS) or 30.0
    src_w      = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    src_h      = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    total_f    = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

    if test_mode:
        max_frames = int(fps * 15)
        total_f    = min(total_f, max_frames)
    else:
        max_frames = total_f

    # ---- Output frame layout ----
    # Left:  original video feed  (src_w x src_h)
    # Right: stats panel on top   (PANEL_W x panel_top_h)
    #        minimap on bottom     (MAP_W   x MAP_H)
    #
    # Right column width = max(PANEL_W, MAP_W)
    RIGHT_W   = max(PANEL_W, MAP_W)
    panel_h   = src_h - MAP_H          # stats panel gets the remaining height
    if panel_h < 80:
        # If video is very short, split equally
        panel_h = src_h // 2
    out_w     = src_w + RIGHT_W
    out_h     = src_h

    fourcc = cv2.VideoWriter_fourcc(*"mp4v")
    writer = cv2.VideoWriter(output_path, fourcc, fps, (out_w, out_h))

    # ---- State ----
    player_stats: dict[int, dict] = defaultdict(lambda: {"shots": 0, "scores": 0})
    total_shots   = 0
    total_scores  = 0
    pulse_effects = []

    # Cooldown tracking (same logic as original SwishAI)
    SHOT_COOLDOWN_FRAMES   = int(fps * 1.5)
    BASKET_COOLDOWN_FRAMES = int(fps * 2.0)
    last_shot_frame:   dict[int, int] = {}   # player_id → last shot frame
    last_basket_frame: int            = -BASKET_COOLDOWN_FRAMES

    basket_center: tuple | None = None   # updated every frame
    frame_idx = 0

    court_base = draw_court_base()   # static base image for minimap

    while frame_idx < max_frames:
        ret, frame = cap.read()
        if not ret:
            break

        # ----------------------------------------------------------------
        # YOLO inference with ByteTrack
        # ----------------------------------------------------------------
        results = model.track(
            frame,
            persist=True,             # keeps track IDs stable across frames
            tracker="bytetrack.yaml", # use ByteTrack (bundled with Ultralytics)
            verbose=False,
            conf=min(conf_map.values()),   # broad pass; we filter per-class below
        )

        res = results[0]

        # Parse detections
        boxes      = res.boxes.xyxy.cpu().numpy()   if res.boxes is not None else []
        class_ids  = res.boxes.cls.cpu().numpy().astype(int) if res.boxes is not None else []
        confs      = res.boxes.conf.cpu().numpy()   if res.boxes is not None else []
        track_ids  = (res.boxes.id.cpu().numpy().astype(int)
                      if res.boxes is not None and res.boxes.id is not None
                      else np.full(len(boxes), -1, dtype=int))

        # ----------------------------------------------------------------
        # Build per-class detection lists (applying per-class conf filter)
        # ----------------------------------------------------------------
        players:        list[tuple] = []   # (box, track_id)
        shooter_boxes:  list[tuple] = []   # (box, track_id)
        ball_boxes:     list        = []
        basket_boxes:   list        = []
        ball_in_basket: bool        = False

        for box, cid, conf, tid in zip(boxes, class_ids, confs, track_ids):
            if conf < conf_map.get(cid, 0.5):
                continue
            if cid == CLASS_PLAYER:
                players.append((box, tid))
            elif cid == CLASS_PLAYER_SHOOT:
                shooter_boxes.append((box, tid))
            elif cid == CLASS_BALL:
                ball_boxes.append(box)
            elif cid == CLASS_BASKET:
                basket_boxes.append(box)
            elif cid == CLASS_BALL_IN_BASKET:
                ball_in_basket = True

        # Update basket center (used for pulse FX)
        if basket_boxes:
            bx1, by1, bx2, by2 = basket_boxes[0]
            basket_center = (int((bx1 + bx2) / 2), int((by1 + by2) / 2))

        # ----------------------------------------------------------------
        # Shot detection — attribute to nearest tracked player
        # ----------------------------------------------------------------
        for shoot_box, shoot_tid in shooter_boxes:
            # Resolve track_id: prefer the tracker-assigned ID,
            # fall back to finding the player bbox with most overlap.
            pid = shoot_tid if shoot_tid >= 0 else _nearest_player_id(
                shoot_box, players)

            if pid < 0:
                continue

            last_f = last_shot_frame.get(pid, -SHOT_COOLDOWN_FRAMES)
            if frame_idx - last_f >= SHOT_COOLDOWN_FRAMES:
                player_stats[pid]["shots"] += 1
                total_shots += 1
                last_shot_frame[pid] = frame_idx

        # ----------------------------------------------------------------
        # Score detection
        # ----------------------------------------------------------------
        if ball_in_basket:
            if frame_idx - last_basket_frame >= BASKET_COOLDOWN_FRAMES:
                last_basket_frame = frame_idx
                total_scores += 1

                # Attribute score to the player who shot most recently
                scorer = _find_recent_shooter(
                    last_shot_frame, frame_idx, BASKET_COOLDOWN_FRAMES * 4)
                if scorer >= 0:
                    player_stats[scorer]["scores"] += 1

                # Pulse FX
                if basket_center:
                    pulse_effects.append(
                        PulseEffect(basket_center, max_radius=90, duration=25))

        # ----------------------------------------------------------------
        # Draw overlays onto the main frame
        # ----------------------------------------------------------------
        annotated = frame.copy()

        if mode in ("full", "stats_effects"):
            # Draw bounding boxes
            if mode == "full":
                for box, tid in players:
                    _draw_player_box(annotated, box, tid, player_stats)
                for box, tid in shooter_boxes:
                    _draw_shooter_box(annotated, box, tid)
                for box in ball_boxes:
                    _draw_ball_box(annotated, box)
                for box in basket_boxes:
                    _draw_basket_box(annotated, box)

            # Pulse effects
            for pulse in pulse_effects:
                pulse.draw(annotated)
            pulse_effects = [p for p in pulse_effects if p.active]

            # Score flash overlay when ball_in_basket
            if ball_in_basket:
                _draw_score_flash(annotated, total_scores)

        # ----------------------------------------------------------------
        # Build right-side panel
        # ----------------------------------------------------------------
        fg_pct = (total_scores / total_shots * 100) if total_shots > 0 else 0.0

        stats_panel = draw_stats_panel(
            player_stats, total_shots, total_scores, fg_pct, panel_h)

        # Minimap
        minimap = court_base.copy()
        if H is not None:
            _draw_players_on_minimap(minimap, players + shooter_boxes,
                                     H, player_stats)

        # Pad minimap to right column width
        minimap_padded = np.zeros((MAP_H, RIGHT_W, 3), dtype=np.uint8)
        minimap_padded[:, :MAP_W] = minimap

        # Pad stats panel to right column width
        stats_padded = np.zeros((panel_h, RIGHT_W, 3), dtype=np.uint8)
        stats_padded[:, :PANEL_W] = stats_panel

        # Stack stats + minimap vertically
        right_col = np.vstack([stats_padded, minimap_padded])
        # Ensure height matches
        if right_col.shape[0] != out_h:
            right_col = cv2.resize(right_col, (RIGHT_W, out_h))

        # Combine left (video) + right (panel)
        combined = np.hstack([annotated, right_col])
        writer.write(combined)

        # ---- Progress update ----
        frame_idx += 1
        progress = int((frame_idx / max_frames) * 100)
        with state_lock:
            processing_state["progress"]     = progress
            processing_state["total_shots"]  = total_shots
            processing_state["total_scores"] = total_scores
            processing_state["fg_percentage"] = fg_pct
            processing_state["player_stats"] = {
                int(k): dict(v) for k, v in player_stats.items()
            }

    cap.release()
    writer.release()

    # Final state
    with state_lock:
        processing_state["status"]      = "completed"
        processing_state["progress"]    = 100
        processing_state["output_file"] = output_path


# ---------------------------------------------------------------------------
# Drawing helpers
# ---------------------------------------------------------------------------

def _draw_player_box(img, box, tid, player_stats):
    x1, y1, x2, y2 = map(int, box)
    color = get_player_color(tid) if tid >= 0 else (200, 200, 200)
    cv2.rectangle(img, (x1, y1), (x2, y2), color, 2)
    stats = player_stats.get(tid, {"shots": 0, "scores": 0})
    label = (f"P{tid}  {stats['scores']}/{stats['shots']}"
             if tid >= 0 else "Player")
    _draw_label(img, label, (x1, y1), color)


def _draw_shooter_box(img, box, tid):
    x1, y1, x2, y2 = map(int, box)
    color = (0, 80, 255)
    cv2.rectangle(img, (x1, y1), (x2, y2), color, 2)
    label = f"P{tid} SHOOT" if tid >= 0 else "SHOOTING"
    _draw_label(img, label, (x1, y1), color)


def _draw_ball_box(img, box):
    x1, y1, x2, y2 = map(int, box)
    cv2.rectangle(img, (x1, y1), (x2, y2), (0, 165, 255), 2)
    _draw_label(img, "Ball", (x1, y1), (0, 165, 255))


def _draw_basket_box(img, box):
    x1, y1, x2, y2 = map(int, box)
    cv2.rectangle(img, (x1, y1), (x2, y2), (0, 255, 200), 2)
    _draw_label(img, "Basket", (x1, y1), (0, 255, 200))


def _draw_label(img, text, pt, color):
    x, y = pt
    (tw, th), _ = cv2.getTextSize(text, cv2.FONT_HERSHEY_SIMPLEX, 0.45, 1)
    y_txt = max(y - 5, th + 4)
    cv2.rectangle(img, (x, y_txt - th - 4), (x + tw + 4, y_txt + 2),
                  (0, 0, 0), -1)
    cv2.putText(img, text, (x + 2, y_txt),
                cv2.FONT_HERSHEY_SIMPLEX, 0.45, color, 1)


def _draw_score_flash(img, total_scores):
    h, w = img.shape[:2]
    overlay = img.copy()
    cv2.rectangle(overlay, (0, 0), (w, h), (0, 200, 255), -1)
    cv2.addWeighted(overlay, 0.08, img, 0.92, 0, img)
    txt = f"SCORE!  {total_scores}"
    (tw, th), _ = cv2.getTextSize(txt, cv2.FONT_HERSHEY_SIMPLEX, 1.8, 3)
    cv2.putText(img, txt,
                ((w - tw) // 2, (h + th) // 2),
                cv2.FONT_HERSHEY_SIMPLEX, 1.8, (0, 200, 255), 3)


def _draw_players_on_minimap(minimap, player_list, H, player_stats):
    for box, tid in player_list:
        foot = _get_foot_point(box)
        map_pt = project_to_minimap(foot, H)
        if map_pt is None:
            continue
        color = get_player_color(tid) if tid >= 0 else (200, 200, 200)
        cv2.circle(minimap, map_pt, 7, color, -1)
        cv2.circle(minimap, map_pt, 7, (255, 255, 255), 1)
        if tid >= 0:
            cv2.putText(minimap, f"P{tid}",
                        (map_pt[0] + 8, map_pt[1] + 4),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.35,
                        color, 1)


def _nearest_player_id(shoot_box, players: list) -> int:
    """Find the track_id of the player bbox with highest IoU to shoot_box."""
    if not players:
        return -1
    best_iou = 0.0
    best_tid = -1
    sx1, sy1, sx2, sy2 = shoot_box
    for pbox, ptid in players:
        px1, py1, px2, py2 = pbox
        ix1 = max(sx1, px1); iy1 = max(sy1, py1)
        ix2 = min(sx2, px2); iy2 = min(sy2, py2)
        inter = max(0, ix2 - ix1) * max(0, iy2 - iy1)
        if inter == 0:
            continue
        union = ((sx2-sx1)*(sy2-sy1) + (px2-px1)*(py2-py1) - inter)
        iou   = inter / union if union > 0 else 0
        if iou > best_iou:
            best_iou = iou
            best_tid = ptid
    return best_tid


def _find_recent_shooter(last_shot_frame: dict, current_frame: int,
                          window: int) -> int:
    """Return the player_id with the most recent shot within `window` frames."""
    best_pid   = -1
    best_frame = -1
    for pid, f in last_shot_frame.items():
        if current_frame - f <= window and f > best_frame:
            best_frame = f
            best_pid   = pid
    return best_pid


# ===========================================================================
#  BACKGROUND WORKER THREAD
# ===========================================================================

def _run_processing(input_path: str, output_path: str, mode: str,
                    test_mode: bool, conf_map: dict):
    global processing_state
    try:
        process_video(input_path, output_path, mode, test_mode, conf_map)
    except Exception as e:
        tb = traceback.format_exc()
        print(f"[SwishAI] Processing error:\n{tb}")
        with state_lock:
            processing_state["status"] = "error"
            processing_state["error"]  = str(e)
    finally:
        # Auto-cleanup uploads
        try:
            os.remove(input_path)
        except OSError:
            pass


# ===========================================================================
#  FASTAPI ENDPOINTS  (identical surface API to original SwishAI)
# ===========================================================================

@app.get("/")
def root():
    return {"message": "SwishAI Extended API is running"}


@app.post("/upload")
async def upload_video(file: UploadFile = File(...)):
    """Accept a video file and save it to the uploads directory."""
    allowed = {".mp4", ".mov", ".avi", ".mkv"}
    suffix  = Path(file.filename).suffix.lower()
    if suffix not in allowed:
        raise HTTPException(400, f"Unsupported format: {suffix}")

    unique_name = f"{uuid.uuid4()}{suffix}"
    save_path   = UPLOAD_DIR / unique_name

    with open(save_path, "wb") as f:
        content = await file.read()
        f.write(content)

    return {"filename": unique_name, "message": "Upload successful"}


@app.post("/process")
def start_processing(req: ProcessRequest):
    """Start background video processing."""
    global processing_state

    with state_lock:
        if processing_state["status"] == "processing":
            raise HTTPException(409, "Already processing a video")

    input_path  = str(UPLOAD_DIR / req.filename)
    if not os.path.exists(input_path):
        raise HTTPException(404, "Uploaded file not found")

    out_name    = f"out_{uuid.uuid4()}.mp4"
    output_path = str(PROCESSED_DIR / out_name)

    conf_map = {
        CLASS_BALL:           req.conf_ball,
        CLASS_BALL_IN_BASKET: req.conf_in_basket,
        CLASS_PLAYER:         req.conf_player,
        CLASS_BASKET:         req.conf_basket,
        CLASS_PLAYER_SHOOT:   req.conf_shoot,
    }

    with state_lock:
        processing_state.update({
            "status":        "processing",
            "progress":      0,
            "output_file":   None,
            "error":         None,
            "player_stats":  {},
            "total_shots":   0,
            "total_scores":  0,
            "fg_percentage": 0.0,
        })

    t = threading.Thread(
        target=_run_processing,
        args=(input_path, output_path, req.mode, req.test_mode, conf_map),
        daemon=True,
    )
    t.start()

    return {"message": "Processing started", "output_file": out_name}


@app.get("/status")
def get_status():
    """Poll processing progress and live stats."""
    with state_lock:
        return JSONResponse(content={
            "status":        processing_state["status"],
            "progress":      processing_state["progress"],
            "total_shots":   processing_state["total_shots"],
            "total_scores":  processing_state["total_scores"],
            "fg_percentage": processing_state["fg_percentage"],
            "player_stats":  processing_state["player_stats"],
            "error":         processing_state["error"],
        })


@app.get("/download/{filename}")
def download_video(filename: str):
    """Download a processed video file."""
    file_path = PROCESSED_DIR / filename
    if not file_path.exists():
        raise HTTPException(404, "Processed file not found")
    return FileResponse(
        str(file_path),
        media_type="video/mp4",
        filename=filename,
    )


@app.delete("/cleanup")
def cleanup():
    """Remove all files from uploads and processed directories."""
    removed = 0
    for d in (UPLOAD_DIR, PROCESSED_DIR):
        for f in d.iterdir():
            try:
                f.unlink()
                removed += 1
            except OSError:
                pass
    return {"message": f"Removed {removed} files"}


# ===========================================================================
#  ENTRY POINT
# ===========================================================================

if __name__ == "__main__":
    uvicorn.run("app:app", host="0.0.0.0", port=8000, reload=False)
